
# makefile (use wmake /ms) to create EditPE.exe
# tools needed:
# - jwasm
# - jwlink
# - wininc
# - HX dev

!include <..\dirs>

name  = EDITPE
name2 = EXTRMZ

!ifndef DEBUG
DEBUG=0
!endif

!if $(DEBUG)
OUTDIR=Debug
AOPTD=-Zi
LOPTD=debug c op cvp
!else
OUTDIR=Release
AOPTD=
LOPTD=
!endif

ASM =@jwasm.exe -c -nologo -coff -Sg -Fl$* -Fo$* $(AOPTD) -I$(HXINST)\Include

ALL: $(OUTDIR) $(OUTDIR)/$(name).EXE $(OUTDIR)\$(name2).EXE

$(OUTDIR):
	@mkdir $(OUTDIR)

$(OUTDIR)/$(name).EXE: $*.obj makefile
	@jwlink @<<
$(LOPTD) format win pe
file $*.obj
name $*.exe 
libpath $(HXINST)\lib
lib { dkrnl32.lib libc32s.lib }
op q,dosseg, m=$*.map, stub=dpmist32.bin $(LOPTD),start=_mainCRTStartup
<<

$(OUTDIR)/$(name).obj: $(name).asm makefile
	$(ASM) $(name).asm

$(OUTDIR)/$(name2).EXE: $*.obj makefile
	@jwlink @<<
format win pe
file $*.obj
name $*.exe 
libpath $(HXINST)\lib
lib { dkrnl32.lib libc32s.lib }
op q,m=$*.map, stub=dpmist32.bin, start=_mainCRTStartup $(LOPTD)
<<

$(OUTDIR)/$(name2).obj: $(name2).asm makefile
	$(ASM) $(name2).asm

clean:
	@del $(OUTDIR)\*.exe
	@del $(OUTDIR)\*.obj
	@del $(OUTDIR)\*.lst
	@del $(OUTDIR)\*.map
