
# Nmake makefile to generate the HX win32 emulation binaries.

# Required tools are:
#
# tool         name         recommended       optional
# --------------------------------------------------------------
# Make                      MS NMake          OW WMake -ms
# Assembler    $(ASM)       JWasm             Masm v6.14+
# COFF linker               JWlink            MS LINK
# COFF lib     $(LIBBIN)    OW WLib           MS LIB
# COFF RC      $(RCBIN)     OW WRC            MS RC
# OMF linker   $(LINK16BIN) JWlink            MS LINK (OMF)
# OMF lib      $(LIB16BIN)  OW WLib           MS LIB (OMF)

# JWasm and JWlink can be found at https://github.com/Baron-von-Riedesel.

# About WSOCK32 target:
# The WSOCK32 target has to be excluded, because some object
# modules are currently missing due to copyright restrictions.
# WSOCK32 is written in C, and requires:
# - OW 32bit C compiler (wcc386.exe)
# - JWlink (jwlink.exe)
# - watt-32 library (WATTCPWD.LIB) compiled with open watcom,
# - OW CRT with register calling convention (clib3r.lib)

# winmm must be create BEFORE dsound
# dddraw must be created BEFORE dciman32

!include <dirs>

!ifndef DEBUG
DEBUG = 0
!endif

ALL: 
    cd COMCTL32
    @$(MAKE) DEBUG=$(DEBUG) 
    cd ..\COMDLG32
    @$(MAKE) DEBUG=$(DEBUG) 
    cd ..\DADVAPI
    @$(MAKE) DEBUG=$(DEBUG) 
    cd ..\DDDRAW
    @$(MAKE) DEBUG=$(DEBUG) 
    cd ..\DCIMAN32
    @$(MAKE) DEBUG=$(DEBUG) 
    cd ..\DGDI32
    @$(MAKE) DEBUG=$(DEBUG) 
    cd ..\DINPUT
    @$(MAKE) DEBUG=$(DEBUG) 
    cd ..\NTLFNHLP
    @$(MAKE) DEBUG=$(DEBUG) 
    cd ..\DKRNL32
    @$(MAKE) DEBUG=$(DEBUG) 
    cd ..\WINMM
    @$(MAKE) DEBUG=$(DEBUG) 
    cd ..\DSOUND
    @$(MAKE) DEBUG=$(DEBUG) 
    cd ..\DUSER32
    @$(MAKE) DEBUG=$(DEBUG) 
    cd ..\IPHLPAPI
    @$(MAKE) DEBUG=$(DEBUG) 
    cd ..\MPR
    @$(MAKE) DEBUG=$(DEBUG) 
    cd ..\MSACM32
    @$(MAKE) DEBUG=$(DEBUG) 
    cd ..\OLE32
    @$(MAKE) DEBUG=$(DEBUG) 
    cd ..\OLEAUT32
    @$(MAKE) DEBUG=$(DEBUG) 
    cd ..\SHELL32
    @$(MAKE) DEBUG=$(DEBUG) 
    cd ..\VERSION
    @$(MAKE) DEBUG=$(DEBUG) 
    cd ..\WSOCK32
    @$(MAKE) DEBUG=$(DEBUG) 
    cd ..\WS2_32
    @$(MAKE) DEBUG=$(DEBUG) 
    cd ..

install: 
	@copy DKRNL32\RELEASE\DKRNL32.DLL ..\Bin
	@copy DKRNL32\DKRNL32.TXT         ..\Doc
	@copy DKRNL32\DKRNLHIS.TXT        ..\Doc

	@copy NTLFNHLP\RELEASE\NTLFNHLP.DLL ..\Bin

	@copy DGDI32\RELEASE\DGDI32.DLL   ..\Bin
	@copy DGDI32\DGDI32.TXT           ..\Doc

	@copy DUSER32\RELEASE\DUSER32.DLL ..\Bin
	@copy DUSER32\DUSER32.TXT         ..\Doc

	@copy DADVAPI\RELEASE\DADVAPI.DLL ..\Bin
	@copy DADVAPI\DADVAPI.TXT         ..\Doc

	@copy DDDRAW\RELEASE\DDDRAW.DLL   ..\Bin
	@copy DDDRAW\DDDRAW.TXT           ..\Doc
	@copy DINPUT\RELEASE\DINPUT.DLL   ..\Bin
	@copy DINPUT\DINPUT.TXT           ..\Doc
	@copy DSOUND\RELEASE\DSOUND.DLL   ..\Bin
	@copy DSOUND\DSOUND.TXT           ..\Doc
	@copy WINMM\RELEASE\WINMM.DLL     ..\Bin
	@copy WINMM\WINMM.TXT             ..\Doc


clean: 
    cd COMCTL32
    @$(MAKE) DEBUG=$(DEBUG) clean 
    cd ..\COMDLG32
    @$(MAKE) DEBUG=$(DEBUG) clean 
    cd ..\DADVAPI
    @$(MAKE) DEBUG=$(DEBUG) clean 
    cd ..\DDDRAW
    @$(MAKE) DEBUG=$(DEBUG) clean 
    cd ..\DCIMAN32
    @$(MAKE) DEBUG=$(DEBUG) clean 
    cd ..\DGDI32
    @$(MAKE) DEBUG=$(DEBUG) clean 
    cd ..\DINPUT
    @$(MAKE) DEBUG=$(DEBUG) clean 
    cd ..\NTLFNHLP
    @$(MAKE) DEBUG=$(DEBUG) clean 
    cd ..\DKRNL32
    @$(MAKE) DEBUG=$(DEBUG) clean 
    cd ..\DSOUND
    @$(MAKE) DEBUG=$(DEBUG) clean 
    cd ..\DUSER32
    @$(MAKE) DEBUG=$(DEBUG) clean 
    cd ..\IPHLPAPI
    @$(MAKE) DEBUG=$(DEBUG) clean 
    cd ..\MPR
    @$(MAKE) DEBUG=$(DEBUG) clean 
    cd ..\MSACM32
    @$(MAKE) DEBUG=$(DEBUG) clean 
    cd ..\OLE32
    @$(MAKE) DEBUG=$(DEBUG) clean 
    cd ..\OLEAUT32
    @$(MAKE) DEBUG=$(DEBUG) clean 
    cd ..\SHELL32
    @$(MAKE) DEBUG=$(DEBUG) clean 
    cd ..\VERSION
    @$(MAKE) DEBUG=$(DEBUG) clean 
    cd ..\WINMM
    @$(MAKE) DEBUG=$(DEBUG) clean 
    cd ..\WSOCK32
    @$(MAKE) DEBUG=$(DEBUG) clean 
    cd ..\WS2_32
    @$(MAKE) DEBUG=$(DEBUG) clean 
    cd ..
