
# NMAKE makefile to create PATCHNE.EXE
# uses JWasm

!include <..\dirs>

!ifndef DEBUG
DEBUG=0
!endif

!if $(DEBUG)
OUTDIR=DEBUG
!else
OUTDIR=RELEASE
!endif

PGM=PATCHNE

ALL: $(OUTDIR) $(OUTDIR)\$(PGM).EXE

$(OUTDIR):
	@mkdir $(OUTDIR)

!if 0

AOPT= -c -nologo -Sg -Fl$* -Fo$* -I$(INC32DIR)

LINK=jwlink.exe

$(OUTDIR)\$(PGM).EXE: $*.obj makefile
	@$(LINK) format dos file $* name $*.EXE op q,map=$*.MAP

$(OUTDIR)\$(PGM).obj: $(PGM).asm makefile
	@$(ASM) $(AOPT) $(PGM).asm

!else

$(OUTDIR)\$(PGM).EXE: $(PGM).asm makefile
	@$(ASM) -nologo -mz -Sg -Fl$* -Fo$*.EXE -I$(INC32DIR) $(PGM).asm

!endif

clean:
	@del $(OUTDIR)\*.exe
#	@del $(OUTDIR)\*.obj
	@del $(OUTDIR)\*.lst
