
# creates DPMI.EXE
# tools used:
# - JWasm

name=DPMI

OUTDIR=RELEASE

ALL: $(OUTDIR) $(OUTDIR)\$(name).EXE

$(OUTDIR):
	@mkdir $(OUTDIR)

$(OUTDIR)\$(name).exe: $(name).asm printf.inc makefile
	@jwasm.exe -mz -nologo -Sg -Fl$* -Fo$* -I..\..\Include $(name).asm

clean:
	@erase $(OUTDIR)\*.exe
