
# creates DPMI.EXE
# tools used:
# - JWasm

!include <..\dirs>

name=DPMI

OUTDIR=RELEASE

ALL: $(OUTDIR) $(OUTDIR)\$(name).EXE

$(OUTDIR):
	@mkdir $(OUTDIR)

$(OUTDIR)\$(name).exe: $(name).asm printf.inc makefile
	@$(ASM) -mz -nologo -Sg -Fl$* -Fo$* -I$(INC32DIR) $(name).asm

clean:
	@erase $(OUTDIR)\*.exe
