
# NMAKE makefile to create PATCHPE.EXE
# uses JWasm

!include <..\dirs>

!ifndef DEBUG
DEBUG=0
!endif

!if $(DEBUG)
OUTDIR=DEBUG
!else
OUTDIR=RELEASE
!endif

PGM=PATCHPE

ALL: $(OUTDIR) $(OUTDIR)\$(PGM).EXE

$(OUTDIR):
	@mkdir $(OUTDIR)

!if 0

LINK=jwlink.exe

AOPT= -c -nologo -Sg -Fl$* -Fo$* -I$(INC32DIR)

$(OUTDIR)\$(PGM).EXE: $*.obj makefile
	@$(LINK) @<<
format dos mz
file $*.obj
name $*.EXE
op map=$*.MAP
<<

$(OUTDIR)\$(PGM).obj: $(PGM).asm makefile
	@$(ASM) $(AOPT) $(PGM).asm

!else

$(OUTDIR)\$(PGM).EXE: $(PGM).asm makefile
	@$(ASM) -mz -c -nologo -Sg -Fl$* -Fo$*.EXE -I$(INC32DIR) $(PGM).asm

!endif

clean:
	@del $(OUTDIR)\*.exe
#	@del $(OUTDIR)\*.obj
	@del $(OUTDIR)\*.lst
#	@del $(OUTDIR)\*.map
