#pmake: build trap lcl os_dos dsx cpu_386 x86

host_os  = dos
host_cpu = i86

os  = dos
srv = hx
cpu = x86
which = TRAP

extra_c_flags = -DHX

!include $(trap_dir)/lcl/dos/dosx/dosx.mif
!include $(trap_dir)/master.mif
