
ExtGetDskFreSpcStruc struct
_size                    dw ?
level                    dw ?
sectorspercluster        dd ?
bytespersector           dd ?
availableclusters        dd ?
totalclusters            dd ?
availablephyssectors     dd ?
totalphyssectors         dd ?
availableallocationunits dd ?
totalallocationunits     dd ?
rsvd                     dd 2 dup (?)
ExtGetDskFreSpcStruc ends

