
VK_BACK    equ 0008h
VK_TAB     equ 0009h
VK_CLEAR   equ 000Ch
VK_RETURN  equ 000Dh
VK_SHIFT   equ 0010h
VK_CONTROL equ 0011h
VK_MENU    equ 0012h
VK_PAUSE   equ 0013h
VK_CAPITAL equ 0014h
VK_ESCAPE  equ 001Bh

VK_SPACE   equ 0020h
VK_PRIOR   equ 0021h
VK_NEXT    equ 0022h
VK_END     equ 0023h
VK_HOME    equ 0024h
VK_LEFT    equ 0025h
VK_UP      equ 0026h
VK_RIGHT   equ 0027h
VK_DOWN    equ 0028h
VK_PRINT   EQU 002Ah

VK_INSERT  equ 002Dh
VK_DELETE  equ 002Eh

VK_LWIN    equ 005Bh
VK_RWIN    equ 005Ch
VK_APPS    equ 005Dh

VK_NUMPAD0    equ 0060h
VK_NUMPAD1    equ 0061h
VK_NUMPAD2    equ 0062h
VK_NUMPAD3    equ 0063h
VK_NUMPAD4    equ 0064h
VK_NUMPAD5    equ 0065h
VK_NUMPAD6    equ 0066h
VK_NUMPAD7    equ 0067h
VK_NUMPAD8    equ 0068h
VK_NUMPAD9    equ 0069h
VK_MULTIPLY   equ 006Ah		;numpad *
VK_ADD        equ 006Bh		;numpad +
VK_SEPARATOR  equ 006Ch		;???
VK_SUBTRACT   equ 006Dh		;numpad -
VK_DECIMAL    equ 006Eh		;numpad . (if Num on)
VK_DIVIDE     equ 006Fh		;numpad / (seems not to work on win98)


VK_F1      equ 0070h
VK_F2      equ 0071h
VK_F3      equ 0072h
VK_F4      equ 0073h
VK_F5      equ 0074h
VK_F6      equ 0075h
VK_F7      equ 0076h
VK_F8      equ 0077h
VK_F9      equ 0078h
VK_F10     equ 0079h
VK_F11     equ 007Ah
VK_F12     equ 007Bh
VK_F13     equ 007Ch
VK_F14     equ 007Dh
VK_F15     equ 007Eh
VK_F16     equ 007Fh
VK_F17     equ 0080h
VK_F18     equ 0081h
VK_F19     equ 0082h
VK_F20     equ 0083h
VK_F21     equ 0084h
VK_F22     equ 0085h
VK_F23     equ 0086h
VK_F24     equ 0087h

VK_NUMLOCK equ 0090h
VK_SCROLL  equ 0091h

VK_LSHIFT	EQU	0A0h
VK_RSHIFT	EQU	0A1h
VK_LCONTROL	EQU	0A2h
VK_RCONTROL	EQU	0A3h
VK_LMENU	EQU	0A4h
VK_RMENU	EQU	0A5h

VK_OEM_1      equ 00BAh  ; ';:' for US
VK_OEM_PLUS   equ 00BBh  ; '+' any country
VK_OEM_COMMA  equ 00BCh  ; ',' any country
VK_OEM_MINUS  equ 00BDh  ; '-' any country
VK_OEM_PERIOD equ 00BEh  ; '.' any country
VK_OEM_2      equ 00BFh  ; '/?' for US
VK_OEM_3      equ 00C0h  ; '`~' for US
VK_OEM_4	  equ 00DBh	 ; '[{' for US
VK_OEM_5	  equ 00DCh  ; '\|' for US
VK_OEM_6	  equ 00DDh  ; ']}' for US
VK_OEM_7	  equ 00DEh  ; ''"' for US
VK_OEM_8	  equ 00DFh  ;
VK_OEM_102	  equ 00E2h  ; "<>" or "\|" on RT 102-key kbd.

