
# Nmake makefile to generate the HX dos extender binaries.

# Required tools are:
#
# tool         name         recommended       optional
# --------------------------------------------------------------
# Make                      MS NMake          OW WMake -ms
# Assembler    $(ASM)       JWasm             Masm v6.14+
# COFF linker               JWlink            MS LINK
# COFF lib     $(LIBBIN)    OW WLib           MS LIB
# COFF RC      $(RCBIN)     OW WRC            MS RC
# OMF linker   $(LINK16BIN) JWlink            MS LINK (OMF)
# OMF lib      $(LIB16BIN)  OW WLib           MS LIB (OMF)

# JWasm and JWlink can be found at http://www.japheth.de.
# The Open Watcom (OW) tools WLib and WRC may also be found
# there - or just download the full OW package.

# About WSOCK32 target:
# The WSOCK32 target has to be excluded, because some object
# modules are currently missing due to copyright restrictions.
# WSOCK32 is written in C, and requires:
# - OW 32bit C compiler (wcc386.exe)
# - JWlink (jwlink.exe)
# - watt-32 library (WATTCPWD.LIB) compiled with open watcom,
# - OW CRT with register calling convention (clib3r.lib)

!include <dirs>

!ifndef DEBUG
DEBUG = 0
!endif

ALL: 
    cd    HDPMI
    @$(MAKE) DEBUG=$(DEBUG) 
    cd ..\DPMILDR
    @$(MAKE) DEBUG=$(DEBUG) 
    cd ..\VESA32
    @$(MAKE) DEBUG=$(DEBUG) 
    cd ..\HXLDR32
    @$(MAKE) DEBUG=$(DEBUG) 
    cd ..\PESTUB
    @$(MAKE) DEBUG=$(DEBUG) 
    cd ..\HXGUIHLP
    @$(MAKE) DEBUG=$(DEBUG) 
    cd ..\SB16
    @$(MAKE) DEBUG=$(DEBUG) 
    cd ..\STUBS
    @$(MAKE) DEBUG=$(DEBUG) 
    cd ..\MZSUPP
    @$(MAKE) DEBUG=$(DEBUG) 
#    cd ..\NESUPP
#    @$(MAKE) DEBUG=$(DEBUG) 
    cd ..\HXHELP
    @$(MAKE) DEBUG=$(DEBUG) 
    cd ..\PATCHPE
    @$(MAKE) DEBUG=$(DEBUG) 
    cd ..\PATCHNE
    @$(MAKE) DEBUG=$(DEBUG) 
    cd ..\SHDPMI
    @$(MAKE) DEBUG=$(DEBUG) 
    cd ..

install: 
	@copy HDPMI\STD16\HDPMI16.EXE   ..\Bin
	@copy HDPMI\STD32\HDPMI32.EXE   ..\Bin
	@copy HDPMI\HDPMIST\HDPMIST.EXE ..\Bin
	@copy HDPMI\HDPMI.TXT           ..\Doc
	@copy HDPMI\HDPMIHIS.TXT        ..\Doc

	@copy DPMILDR\STD16\DPMILD16.EXE   ..\Bin
	@copy DPMILDR\STD32\DPMILD32.EXE   ..\Bin
	@copy DPMILDR\STUB16\DPMILD16.BIN  ..\Bin
	@copy DPMILDR\STUB32\DPMILD32.BIN  ..\Bin
	@copy DPMILDR\STUBX16\HDLD16.BIN   ..\Bin
	@copy DPMILDR\STUBX32\HDLD32.BIN   ..\Bin
	@copy DPMILDR\NOLFN32\DPMILD32.EXE ..\UnSupp
	@copy DPMILDR\DPMILD16.TXT         ..\Doc
	@copy DPMILDR\DPMILD32.TXT         ..\Doc

	@copy STUBS\Release\DPMIST16.BIN ..\Bin
	@copy STUBS\Release\DPMIST32.BIN ..\Bin
	@copy STUBS\Release\LOADPE.BIN   ..\Bin
	@copy STUBS\Release\LOADPEX.BIN  ..\Bin
	@copy STUBS\Release\LOADPXNR.BIN ..\Bin
	@copy STUBS\STUBS.TXT            ..\Doc

	@copy HXLDR32\Release\HXLDR32.EXE ..\Bin
	@copy HXLDR32\Release\HXDOSLD.EXE ..\Bin
	@copy HXLDR32\HXLDR32.TXT         ..\Doc
	@copy HXLDR32\HXDOSLD.TXT         ..\Doc

	@copy PATCHPE\Release\PATCHPE.EXE ..\Bin
	@copy PATCHPE\PATCHPE.TXT         ..\Doc

	@copy PESTUB\Release\PESTUB.EXE   ..\Bin
	@copy PESTUB\PESTUB.TXT           ..\Doc

	@copy SB16\Release\SB16.DLL       ..\Bin
#	@copy SB16\SB16.TXT               ..\Doc

	@copy VESA32\Release\VESA32.DLL   ..\Bin
	@copy VESA32\VESA32.TXT           ..\Doc

clean: 
    cd    HDPMI
    @$(MAKE) DEBUG=$(DEBUG) clean
    cd ..\DPMILDR
    @$(MAKE) DEBUG=$(DEBUG) clean
    cd ..\VESA32
    @$(MAKE) DEBUG=$(DEBUG) clean 
    cd ..\HXLDR32
    @$(MAKE) DEBUG=$(DEBUG) clean 
    cd ..\PESTUB
    @$(MAKE) DEBUG=$(DEBUG) clean 
    cd ..\HXGUIHLP
    @$(MAKE) DEBUG=$(DEBUG) clean 
    cd ..\SB16
    @$(MAKE) DEBUG=$(DEBUG) clean 
    cd ..\MZSUPP
    @$(MAKE) DEBUG=$(DEBUG) clean 
#    cd ..\NESUPP
#    @$(MAKE) DEBUG=$(DEBUG) clean 
    cd ..\STUBS
    @$(MAKE) DEBUG=$(DEBUG) clean 
    cd ..\HXHELP
    @$(MAKE) DEBUG=$(DEBUG) clean 
    cd ..\PATCHPE
    @$(MAKE) DEBUG=$(DEBUG) clean 
    cd ..\PATCHNE
    @$(MAKE) DEBUG=$(DEBUG) clean 
    cd ..\SHDPMI
    @$(MAKE) DEBUG=$(DEBUG) clean 
    cd ..
