
# this will create OLEAUT32.DLL
# adjust paths in file "..\dirs" first!
# to create a debug version use "nmake debug=1"
# output will be in subdir RELEASE or DEBUG, format
# of object modules is COFF format, true flat

!include <..\dirs>

!ifndef DEBUG
DEBUG=0
!endif

!if $(DEBUG)
AOPTD=-D_DEBUG
OUTDIR=DEBUG
!else
AOPTD=
OUTDIR=RELEASE
!endif

SRCMODS = \
!include modules.inc

OBJMODS = $(SRCMODS:.ASM=.OBJ)
!if $(DEBUG)
OBJMODS = $(OBJMODS:.\=DEBUG\)
!else
OBJMODS = $(OBJMODS:.\=RELEASE\)
!endif

AOPT= -c -coff -nologo -Sg $(AOPTD) -I$(INC32DIR) -D?FLAT=1 -Fl$* -Fo$* 

LOPTS= /NOLOGO /MAP /SUBSYSTEM:CONSOLE /DLL /LIBPATH:$(LIBCOFF)

NAME=OLEAUT32
LIBNAME=OLEAUTOS

LIBS=dkrnl32.lib duser32.lib

.SUFFIXES: .asm .obj

.asm{$(OUTDIR)}.obj:
	@$(ASM) $(AOPT) $<

ALL: $(OUTDIR) $(OUTDIR)\$(NAME).DLL

$(OUTDIR):
	@mkdir $(OUTDIR)

$(OUTDIR)\$(NAME).DLL: $(OUTDIR)\$(LIBNAME).lib $(OUTDIR)\$(NAME).obj $(NAME).def $(NAME).rsp Makefile
!if $(MSLINK)
	@link @<<
$(OUTDIR)\$(NAME).obj $(OUTDIR)\$(LIBNAME).lib $(LIBS)
$(LOPTS) $(LOPTD)
/DEF:$(NAME).def /OUT:$*.DLL
<<
!else
	@$(LINKBIN) format win pe dll name $*.DLL f $(OUTDIR)\$(NAME).obj LIBPATH $(LIBCOFF) lib {$(OUTDIR)\$(LIBNAME).lib $(LIBS)} op q, map=$*, implib=$* @$(NAME).rsp
!endif

WLIBMODS=$(SRCMODS:.\=+)

$(OUTDIR)\oleautos.lib: $(OBJMODS)
	@cd $(OUTDIR)
	@$(LIBBIN) @<<
$(LIBNAME).LIB $(WLIBMODS:.ASM=.OBJ)
<<
	@cd ..

clean:
	@del $(OUTDIR)\*.obj
	@del $(OUTDIR)\*.dll
	@del $(OUTDIR)\*.lib
	@del $(OUTDIR)\*.lst
