
!include <..\dirs>

ALL:
	$(MAKE) -s -f DOSXXX.MAK
	$(MAKE) -s -f DOSCALLS.MAK
	$(MAKE) -s -f NLS.MAK
	$(MAKE) -s -f VIOCALLS.MAK
	$(MAKE) -s -f KBDCALLS.MAK
#	$(MAKE) -s -f MOUCALLS.MAK

clean:
	$(MAKE) -s -f DOSXXX.MAK    clean
	$(MAKE) -s -f DOSCALLS.MAK  clean
	$(MAKE) -s -f NLS.MAK       clean
	$(MAKE) -s -f VIOCALLS.MAK  clean
	$(MAKE) -s -f KBDCALLS.MAK  clean
#	$(MAKE) -s -f MOUCALLS.MAK  clean
